// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from 'prisma/config';
import dotenv from 'dotenv';

if (!process.env.DATABASE_URL) {
  dotenv.config();
}

// Detect test environment
const isTest = process.env.NODE_ENV === 'test';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: isTest
      ? 'postgresql://postgres:postgres@localhost:5432/makerbox_test?schema=public'
      : process.env.DATABASE_URL,
  },
});
