name: Pruebas del Proyecto

on:
  pull_request:
    branches: [ main ]

jobs:
  check-codigo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test