name: CI 

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Instalar dependencias
      run: npm install

    - name: Instalar dependencias del Backend
      run: cd backend && npm install
    
    # Nota: Asegúrate de que la carpeta se llame 'fronted' o cámbialo a 'frontend'
    - name: Instalar dependencias del frontend
      run: cd fronted && npm install

    - name: Generar cliente de Prisma
      run: npx prisma generate --schema=./backend/prisma/schema.prisma
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}

    - name: Verificar Build del Backend
      run: cd backend && npm run build

    - name: Verificar Build del Frontend
      run: cd fronted && npm run build

    - name: Ejecutar Lint
      run: npm run lint
      
    - name: Ejecutar Pruebas Unitarias y Cobertura (Backend)
      run: cd backend && npm run test:cov

    - name: Subir reporte a Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./backend/coverage