name: CI 


on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]


jobs:
  build-and-test:
 
    runs-on: ubuntu-latest

 
    steps:
 
    - name: Checkout del código
      uses: actions/checkout@v4

 
    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'


    - name: Instalar dependencias
      run: npm install

    - name: Instalar dependencias del Backend
      run: cd backend && npm install
    
    - name: Instalar dependencias del fronted
      run: cd fronted && npm install

    - name: Verificar Build del Backend
      run: cd backend && npm run build

    - name: Verificar Build del Frontend
      run: cd fronted && npm run build

    - name: Generar cliente de Prisma
      run: npx prisma generate --schema=./backend/prisma/schema.prisma


    - name: Ejecutar Lint
      run: npm run lint
  
  analisis-calidad:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Correr Super-Linter
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          USE_FLAT_CONFIG: true

          FILTER_REGEX_EXCLUDE: (.*eslint\.config\..*|.*package-lock\.json)

          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_JSON: true
          VALIDATE_YAML: true
  ## Falta crear test